FROM node:21-alpine3.19 as deps

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci


FROM node:21-alpine3.19 as build

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules

COPY . .

RUN npm run build


FROM node:21-alpine3.19 as prod

WORKDIR /app

COPY package.json package-lock.json ./

# Instalar solo dependencias de producción (sin devDependencies)
RUN npm ci --omit=dev

COPY --from=build /app/dist ./dist

USER node

CMD ["node", "dist/main.js"]
